/*

OPERADORES LÓGICOS E CONDICIONAIS

Write a JavaScript program to check whether a given positive number is a multiple of 3 or a multiple of 7.

link: https://www.w3resource.com/javascript-exercises/javascript-basic-exercise-25.php

*/
/*
function test37(x) 
{
  if (x % 3 == 0 || x % 7 == 0) 
  {
    return true;
  } 
  else {
    return false;
  }
}

console.log(test37(12));
console.log(test37(14));
console.log(test37(10));
console.log(test37(11));
*/

if (x % 3 == 0 || x % 7 == 0) 
  {
    return true;
  } 
  else {
    return false;
  }
